# Ignore this file if you are not using Gitpod
image:
  file: .gitpod.Dockerfile

tasks:
  - init: curl -sSL https://install.python-poetry.org | python3 -
  - init: poetry install
  - command: poetry run python main.py

vscode:
  extensions:
    - saoudrizwan.claude-dev
